### ISSUE TITLE
How can I log info in the chrome devtoll when start nodejs with --inspect

### ISSUE THREAD

**Issue by mqliutie** [debug-js/debug#856]
I know in node environment log use this log function

```
function log(...args) {
	return process.stderr.write(util.format(...args) + '\n');
}
```
Messages shown in the terminal is correct.

But In my app which is build by electron, I want to know log messages only use --inspect to start app, but message will never be shown in the chrome://inspect devtool. 

So, is there a way to do that?

**Comment by Qix-** [comment]
You'll have to ask the Electron team, sorry. I don't know enough about the inspector protocol with Electron to know.
