### ISSUE TITLE
debug output not captured by services like LogRocket

### ISSUE THREAD

**Issue by ffxsam** [debug-js/debug#865]
I was under the impression that `debug` (browser side) uses `console.debug` to dump logs, but strangely, LogRocket doesn't record these. I did a test just using `console.debug()` directly and I see those in LogRocket.

Is `debug` doing something special/different here?

**Comment by Qix-** [comment]
Nope. https://github.com/debug-js/debug/blob/master/src/browser.js#L181-L189

**Comment by ffxsam** [comment]
Thanks!

**Comment by ffxsam** [comment]
Update: It's because LogRocket captures console.debug after `debug` has already stored its own reference to it. So I just have to import `debug` after LogRocket is initialized.
