### ISSUE TITLE
Debug shows different timestamp formats across package and project

### ISSUE THREAD

**Issue by ihack2712** [debug-js/debug#867]
Debug shows different timestamp formats for body-parser, express and my project.

![image](https://user-images.githubusercontent.com/35933830/152606813-470839a4-75db-4e6e-8637-3980abf0ac12.png)

![image](https://user-images.githubusercontent.com/35933830/152606886-61060ef7-dd90-4296-80ad-4b174a3491f1.png)

![image](https://user-images.githubusercontent.com/35933830/152606961-a42f1243-97f4-4280-aed4-01ef8d363bd4.png)

**Comment by ihack2712** [comment]
I also attempted to use the override feature, did not work though.

![image](https://user-images.githubusercontent.com/35933830/152607024-a95eb286-38fe-4691-9fe2-b2e636aa7ba7.png)

**Comment by Qix-** [comment]
Mrh yeah sorry about that. I'm still trying to figure out the best way to fix this problem.

**Comment by ihack2712** [comment]
Ah I see, so if I understand correctly, this is Express' doing?

**Comment by ihack2712** [comment]
![image](https://user-images.githubusercontent.com/35933830/152608220-d64f6012-85be-4563-99a9-5ff92b5ac339.png)

For some reason, when degrading to 2.6.9 (the same version express depends on) my logs use the GMT format, and express' logs uses the timestamp format.

Weird..

**Comment by Qix-** [comment]
What does `npm ls debug` show?

**Comment by ihack2712** [comment]
![image](https://user-images.githubusercontent.com/35933830/152609686-f8b2166c-d5bd-44f1-93af-fdbf12119112.png)

**Comment by Qix-** [comment]
Not sure that `^` is allowed in overrides. Maybe start with just

```json
{
    "overrides": {
        "debug@2.6.9": {
            "debug": "4.3.3"
        }
    }
}
```

Does that work?

**Comment by ihack2712** [comment]
![image](https://user-images.githubusercontent.com/35933830/152610309-f32d69ca-eb07-421c-959f-cac1876baf7f.png)


![image](https://user-images.githubusercontent.com/35933830/152610330-0d4b44c6-20cc-431c-b6a4-991e4abeb8dc.png)

**Comment by Qix-** [comment]
No idea then :/ Which order are you importing `debug`? Do you first import it before or after `express`? If after, try importing it before anything else.

**Comment by Qix-** [comment]
Actually looking at your `npm ls` output it doesn't appear the override is working. Are you using package-lock.json files per chance?

Try deleting it (I have them turned off by default) then re-installing.

**Comment by ihack2712** [comment]
Yes, I'll delete the lockfile and try again ;)

**Comment by ihack2712** [comment]
Okay, so for some reason my own debugs no longer work - but express' do

**Comment by Qix-** [comment]
By "not work" do you mean just no output? Or is there an error?

Try blowing away both `node_modules` *and* any lockfiles and re-installing from scratch, then.

**Comment by ihack2712** [comment]
![image](https://user-images.githubusercontent.com/35933830/152610919-4d2b7267-3b2a-4e8d-86ee-47be5d3728be.png)

Got them back

It didn't output, even though DEBUG was set to `*`, it was because dotenv was loaded after debug I think

**Comment by ihack2712** [comment]
The override still doesn't work

**Comment by ihack2712** [comment]
``json
  "overrides": {
    "express": {
      "debug": "4.3.3"
    },
    "nodemon": {
      "debug": "4.3.3"
    },
    "apollo-server-express": {
      "body-parser": {
        "debug": "4.3.3"
      }
    }
  }
```

Turns out this was the way to go, it works using this. Probably time to do a couple of version bump PRs

**Comment by Qix-** [comment]
Oh right, that makes sense 🙃 sorry I didn't catch it the first time haha.

Yeah seems right! Feel free to ping me on any you may open.

Going to go ahead and close this now. Let me know if there's anything else.

**Comment by ihack2712** [comment]
Awesome, thanks for your help, awesome library!
