### ISSUE TITLE
error while trying to install browser sync using cpm

### ISSUE THREAD

**Issue by loveth5** [debug-js/debug#870]
Hi i had an error with trying to install browser sync using cpm on windows
here's the error below
 deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)

**Comment by Qix-** [comment]
Yeah it's not an error, it means you need to upgrade `debug`.

**Comment by loveth5** [comment]
How will I upgrade debug
How do I go about the ugrade

**Comment by loveth5** [comment]
I tried upgrading debug through various mens, but, it's to no avail

The jpegs sent after this are results of the upgrade😔
What am I not getting, I'm curious🤔

**Comment by Qix-** [comment]
I don't know anything about cpm, sorry. You need to research how to upgrade packages, this isn't the place to ask such questions.
