### ISSUE TITLE
debug.enable() NOT dynamic

### ISSUE THREAD

**Issue by KevinAst** [debug-js/debug#871]
I am new to debug logger and I thank you for your awesome utility.

In my experience, using `debug.enable('myProj:myModule:myFn')` **does NOT dynamically impact the logging filters** in the current process _(in either the browser or node)_.  It merely resets the DEBUG env var _(or the browser's localStorage.debug)_.  The process must then be re-started for it to take effect.

I am using the latest 4.3.3 release.

I must be doing something wrong, as the README docs clearly state that `enable()` dynamically resets the filter.

The ability to dynamically change the logging filters _(without restarting the process)_ is a crucial feature for production code, especially in a node/server environment.

I have searched both the debug project issues -and- stackoverflow with no luck.  I did find a number of `enable()` issues, but none that seemed to match my problem.

One thing I considered is I am creating my log instances in a "module scope", so my probes live a lifetime in the process.  **Is this an incorrect usage?**  Should I be creating log instances in a function scope, so they are re-created on each function invocation?  I tried a quick test of this, and it seemed the results were the same _(still no dynamic behavior)_.

From an application perspective, this feature would seem to be very rudimentary ... so as I stated, I must be doing something wrong.

Any help would be greatly appreciated.

**Comment by Qix-** [comment]
It might be the case, honestly. Using `debug.enable()` is very highly discouraged and hasn't worked "correctly" since it was written. I know that's probably not the answer you want to hear.

You should be using the `DEBUG` environment variable whenever possible. Setting individual debugger `enabled` properties should also work correctly. The top-level `debug.enable()` function is a mine field and has multiple documented issues.

**Comment by KevinAst** [comment]
Thanks for your quick response @Qix.

FYI: When I used the term "rudimentary", I was not implying that it was easy to implement, rather that it's usage was easy _(not understanding how I messed it up :-)_

## Background

Certainly in a development environment it is feasible to use the DEBUG env var.  However I am working on a server administrative utility that provides the ability to dynamically alter the filters in a production deployment _(without re-starting the server)_.  In this context, the `debug.enable()` feature is crucial in diagnosing unexpected conditions in production.


## Regarding My Problem

For what it is worth, I just now partially resolved my problem.  I had a dream about this last night _(I do my best work in my sleep :-)_.

I thought I had it fixed fix, but it is still very problematic _(as you say a "mine field")_.

My project is a MonoRepo, where I am using the `debug` logging utility in multiple packages.  The way in which I am managing the MonoRepo, I ended up with multiple `debug` instances, which (I believe) manifested itself in the behavior I was seeing.

This would explain how `debug.enable(...)`

 - changed `localStorage.debug` ... because this is more of a global state

 - but did not dynamically change the filters of the logging probes that were created through a different `debug` instance!

My attempted fix was to promote a single `debug` instance from a central utility _(promoted by ONE of my MonoRepo packages)_.

I was able to get it working correctly on my Svelte client, however had NO success on my Node server.  I suspect this problem is further compounded by the fact that my server dependency (Express) also uses `debug`.

Thoughts?


## Mine Field Future?

Regarding the `debug.enable()` "mine field", are there plans to shore shore this up _(possibly in a major release)_?  As I mentioned, this is a crucial feature for projects that are retaining their logging probes in production.


## Misc Questions

If you would be so kind, I would appreciate you insight on a couple of questions regarding performance ...

Question 1: Is the overhead of debug's "pure logging functions" fairly minimal when disabled?  Have you done any performance tests on this?  I'm using the term **pure** so as to **omit** any overhead incurred by the app-level message generation _(I realize the app must add defensive measures to prevent that overhead when the log is disabled)_.  Performance is certainly relevant for projects that intend to leave their logging probes in-place for production.

Question 2: Speaking of performance ... there are cases where I want to use a distinct log namespace for a specific function _(within a module)_ ... EX: "myApp:myModule:myFunction".  In this case, is it OK _(from a performance perspective)_ to create the log in that function scope _(where it would be re-created on each function invocation)_, or should I create all the logs at one time _(in the module scope)_ and use the appropriate log in each function?

Question 3: Is there a way to obtain the current logging filter from the debug API?  I realize I can glean this _(initially)_ from the env var, but I would prefer to get it from the horses mouth _(i.e. the debug API)_.  I noticed that `debug.disable()` returns this information.  I suppose I could run disable() _(to get the filter)_ and then run enable() with that same filter, but that seems rather hacky.  I may have missed it, but that simple feature would be nice one to add to the list of enhancements.


## Thanks

Thanks in advance, for putting up with all my questions, thanks again for this awesome utility!

**Comment by Qix-** [comment]
> are there plans to shore shore this up

Yes, quite a few issues are open about it. Checked the pin roadmap issue #656 which mentions the various pieces of the `.enable()` puzzle.
