### ISSUE TITLE
Allowing debug only in dev environment

### ISSUE THREAD

**Issue by derekgould** [debug-js/debug#872]
What is the best-practices approach for disabling debug statements in a production environment? 

We use development, Staging and Production environments, so we'd like to have the debug statements working for Dev and Staging, but disabled completely in production. What's the recommended way to accomplish that?

**Comment by Qix-** [comment]
The correct way to use this library is this:

- Never use `debug.enable()`. It should have never made it into the API but alas I can't change that. The "default" mode of operation should be that log statements do not appear at all.
- Only define `DEBUG` environment variable in development/test/stage/whatever environments. Omit it or explicitly `unset DEBUG` in production.

Hope that helps!
