### ISSUE TITLE
Azure function deployment issue

### ISSUE THREAD

**Issue by lloedolff** [debug-js/debug#881]
Good day.
I am getting inconsistence issues when deploying jsReportst to Azure. I am using the latest version of the git repository as of the time of posting this questions.
When deploying with 5 reports, everything works perfectly, but when i deploy with 17 reports (using a valid license), I am getting random errors, including a blank page as a response, an error saying that is can't find the report's css file and an error saying that the report can't be found.
The odd thing is that it is not consistent, so one minute i would get the css error and 5 minutes later it would say it can't find the reports.

Has anyone else experienced this kind of behaviour?

Thanks in advance.

**Comment by Qix-** [comment]
This has absolutely nothing to do with this repository.
