### ISSUE TITLE
conditional log based on ms value (or any other custom logic)

### ISSUE THREAD

**Issue by axyz** [debug-js/debug#885]
Hi, was wondering if it is possible to only show logs for events that take more than X ms, that would be helpful to identify bottlenecks in an application with many log points and eventually namespace such logger as app:perf for example.

I was thinking that could be done with a custom formatter, but quickly looking at the code it seems that the the new line is always inlcuded.

Maybe I'm missing something and there is a better way to achieve that, or is it a use case that was never considered?

**Comment by Qix-** [comment]
This would be a case for #556. No estimate on when it'll be ready though, unfortunately. Right now you'd have to override the `.log` function to handle that logic yourself, which I know isn't ideal.

Going to close in favor of the linked issue, let me know if I can answer any more questions.
