### ISSUE TITLE
automatic set of the current filename / module name 

### ISSUE THREAD

**Issue by ZeeD** [debug-js/debug#889]
Hi.
I just found your project and I like it and how you can use it to "protect" under a env var the internal logging.
I would like to understand if it's possible to configure it just once to automatically set a "template" format, or create some importable wrapper.
 My end goal is to have a `debug` method that would be created "automagically" with the name of my project and the name of the current file / module.
At the moment I have this snippet I "copy and paste" all over the files I have in my project, but its ugly and cumbersone.

```typescript
import debugModule from 'debug';
import { parse } from 'path';
const debug = debugModule(`my-project:${parse(__filename).name}`);
```

Ideally I would like to write

```typescript
import debug from 'debug';
```

having somewhere a `debug.config.js` file with some configuration like
```json
{
    "project": "my-project",
    "namespace-rule": "module"
}
```
or something that could let me express the fact that if I'm in `foo.ts` I want `debug` to automatically use the namespace `my-project:foo`

**Comment by Qix-** [comment]
Nope, this is something that's not possible. I'm not sure how useful it would be for most people's use cases and it'd introduce a lot of startup overhead in the general case.

Good question though :)

**Comment by Leftium** [comment]
My [@leftium/gg](https://github.com/Leftium/gg) module automatically sets the namespace based on filename+function name. It used to be built on top of this debug module, but now uses an internal TS port of debug with some minor mods (moved ms diff to beginning of output; also ported/passes all relevant debug tests!)

There are two ways this was achieved:
- **Currently:** At *build-time* an optional Vite plugin rewrites calls to gg() with the meta info (expression, function name, filename, line number, column number, etc...)
- **Previously:** At runtime, the call stack was parsed for the meta info.

**Live demo:** https://gg.leftium.com/?gg

**Screenshot:** (The GG dev console is optional, but supports richer output.)

<img width="854" height="889" alt="Image" src="https://github.com/user-attachments/assets/56b013d3-c194-46c5-b025-f2fd5dcb793b" />
