### ISSUE TITLE
Some colors illegible in Chrome console

### ISSUE THREAD

**Issue by ffxsam** [debug-js/debug#902]
It would be nice if we could add certain colors or color brightness to a blocklist. In dark mode, some of these colors are very difficult to read in the Chrome DevTools console.

<img width="618" alt="CleanShot 2022-07-19 at 15 16 51@2x" src="https://user-images.githubusercontent.com/12532733/179840533-0ea74160-4149-40cb-b7fb-08bbda139690.png">

**Comment by ffxsam** [comment]
(or better yet, use a library like `tinycolor2` to determine color contrast of a chosen color against the background, and choose another color if the contrast is too low)

**Comment by Qix-** [comment]
There's no way to get the background of the devtools console, so there's no sane way to do this. Same problem exists in the terminal.
