### ISSUE TITLE
npm:debug:4.3.4 is vulnerable Cx8bc4df28-fcf5 7.5 Inefficient Regular Expression Complexity vulnerability pending CVSS allocation

### ISSUE THREAD

**Issue by dwclogic** [debug-js/debug#929]
Message about Dependancy issue detected:  

- Dependency npm:debug:4.3.4 is vulnerable Cx8bc4df28-fcf5 7.5 Inefficient Regular Expression Complexity vulnerability pending CVSS allocation  Results powered by Checkmarx(c) 

I'm not finding on the internet about the specific error.   Searched "issues" for "regular expression complexity" got nothing.

**Comment by Qix-** [comment]
#921
