### ISSUE TITLE
Project considered abandoned?

### ISSUE THREAD

**Issue by danawoodman** [debug-js/debug#930]
Can it be safe to assume that `debug` is effectively abandoned?

The last npm release was over a year ago, there are 19 open PRs and the [discussion about v5 seems stalled/dead](https://github.com/debug-js/debug/issues/656).

Not trying to troll, just trying to get a feel if I should start looking elsewhere.

**Comment by Qix-** [comment]
No, it's not abandoned. It's still waiting on Node.js to unblock features for a v5 rollout, as has been mentioned elsewhere.

There are one of two courses of action moving forward, however:

1. Node.js includes proper flags for supporting our usecase for the v5 refactor
2. `debug` is officially sunset, deprecated, and archived, and further use is discouraged everywhere in the ecosystem.

If this project ever dies, it'll be officially killed, not trail off into nothing. Right now I'm still waiting to see if anything will happen, but I don't have a lot of hopes.

**Comment by danawoodman** [comment]
@Qix- thanks for the qik (get it?) reply!

Is there a ticket I can look at to learn more?
