### ISSUE TITLE
Issue in Next.js

### ISSUE THREAD

**Issue by mledwards** [debug-js/debug#944]
I've added this debug line to the server side template`layout.tsx` of a Next.js v13.5 project, and I'm getting this error.
![image](https://github.com/debug-js/debug/assets/2692615/8abcb7a9-0aea-46ed-b286-2425b495d890)

Any ideas what could be causing this?

**Comment by Qix-** [comment]
`debug` is an ESM package. Try using `import`.

**Comment by Qix-** [comment]
Going to close this unless there's something else!

**Comment by mledwards** [comment]
> `debug` is an ESM package. Try using `import`.

I changed this, but got the same issue.

I think the problem is this line `DEBUG: process.env.NODE_ENV === "development" ? "boilerplate:*" : "",` line. In Next 13.4+ App Router approach, you don't actually need it anymore, just setting the DEBUG env var seems to work.

Thanks for the response!

**Comment by jyunhanlin** [comment]
https://github.com/debug-js/debug/blob/master/src/node.js#L205

It seems the code will cause Next.js to fail when using `DEBUG=xxx:* npm run dev`
When I comment it, the issue is gone.
