### ISSUE TITLE
Anyone knows worth alternative for the golang?

### ISSUE THREAD

**Issue by fedulovivan** [debug-js/debug#970]
Sorry for posting offtop, but think this may be usefull for everyone who used to work in js world and now switching to golang.

So the question is, is there anything similar to nodejs's "debug" library, created for golang?

**Comment by Qix-** [comment]
There are many logging libraries, I'm sure. However, this library _isn't_ the best design for a logging library, and I don't encourage people in other languages to adopt how `debug` works. SLF4J (Java), the `log` crate (Rust), etc. are much better designs that are more library friendly and don't encourage renegade logging systems to compete like `debug` does.

Going to close, however, as this isn't the place for this sort of conversation. Best of luck :)
